version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: "mysql:5.7"
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  devops_project:
    build:
      context: ./
      dockerfile: Dockerfile
    image: medalibouderbela/achat:AchatBackend
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - 8089:8089
    depends_on:
      - mysqldb

